[package]
name = "tc200"
version = "0.1.0"
authors = ["kkao99 <38305127+kkao99@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
